### ISSUE TITLE
E-mail validation doesn't take into account new TLDs

### ISSUE THREAD

**Issue by bardzusny** [jbandura/ember-legit-forms#20]
Current [emailRegex](https://github.com/jbandura/ember-legit-forms/blob/master/addon/validators/email-validator.js#L9) doesn't validate e-mail addresses in new top-level domains, like:
- john@doe.accountant
- come.to@awesome.work
- andrea@rotfl.xxx

Possible solutions that I can see:
- Use different, more tolerant regular expression for validation - like the one described [here](http://www.regular-expressions.info/email.html) (_"99.99% of addresses in actual use today"_).
- Go for delegating the task to external library, like [isemail](https://github.com/hapijs/isemail) (or one of _many_ others).
- Or plunge ahead and do the same for all other validations, for consistency ([validate.js](https://validatejs.org/) seems like first choice for that).

Will be happy to submit PR once we decide on the best option - to me it looks like unavoidable choice between under-100% RFC 5322 conformance or way too much code bloat for something supposedly so simple, after all.

Any comments?

**Comment by michalsnik** [comment]
Just for the record I encountered the same issue and solved it by using following regex:
```
([\w-\.]+)@((?:[\w]+\.)+)([a-zA-Z]{2,})
```
I believe this should be more than enough for front-end validation part.

**Comment by michalsnik** [comment]
@jbandura what do you think? I'd be happy to push this this forward as well as @bardzusny :)

**Comment by jbandura** [comment]
unfortunately this sits on my to-do list for quite some time :) If you have some time to do that I'd greatly appreciate it! If not I'll try to get this out of the way as soon as I'll manage to find some free time :)
