### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by bardzusny** [jbandura/ember-legit-forms#29]
Inspired by https://github.com/jbandura/ember-legit-forms/pull/25 - PR which removed `ember-getowner-polyfill` dependency, unnecessary since Ember.JS 2.3 release.

Does it mean we should do the same about `ember-get-helper`, which is available since Ember.JS 2.0 (see https://github.com/jbandura/ember-legit-forms/blob/master/package.json#L54 )? I'll be happy to submit PR with that change.

(Also, I wanted to create this issue to bring up the fact that this is kinda backwards-incompatible change, at risk of breaking legacy applications with older Ember.JS versions running. If we're to follow strict semantic versioning, would it mean new major version? Food for thought.)

**Comment by jbandura** [comment]
solved by #30 and #25 :)
