### ISSUE TITLE
Translations issue when not present

### ISSUE THREAD

**Issue by michalsnik** [jbandura/ember-legit-forms#37]
Hi @jbandura, I just encountered minor issue.
When you install `ember-i18n` but don't add any translations `ember-legit-forms` doesn't use default translations and expects custom ones instead.

I think it should not only check if there is `Ember.i18n`, but rather if there are actual custom translations as well, if not -> then provide with default ones. Otherwise it should expect custom. WDYT?

Right now I have `ember-i18n` installed, but I want to use default translation without copying them to my translations and it's not possible.

**Comment by jbandura** [comment]
good point! Will fix it this week/weekend

**Comment by jbandura** [comment]
This definitely took longer than "this week" 😅  Thanks once more for submitting this @michalsnik 👍
