### ISSUE TITLE
Disabling selecting default "--select--" option on lf-select

### ISSUE THREAD

**Issue by kdamball** [jbandura/ember-legit-forms#66]
Current behaviour:
- There's no way of disabling `--select--` or the placeholder option in `lf-select`

Expected behaviour:
- An option to disable it. Otherwise, it will just be there to raise validation errors :)
- See this as an example on how to hide it: http://jsbin.com/kohelunefe/1/edit?html,output

Thanks

**Comment by jbandura** [comment]
Thanks for reporting :) Fixed in #68 - will be released in 2.2.0 :)

**Comment by jbandura** [comment]
Released in 2.2.0 🚀
